import {
    Button,
    StandardButton,
    AboutSlint,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";

export component AboutDialog inherits Dialog {
    title: "About";
    in property <string> version;
    in property <string> home_page;
    in property <string> license;
    in property <length> text-font-size: self.default-font-size;
    icon: @image-url("resources/icons/info.svg");
    callback close();
    VerticalBox {
        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 0.0;
            font-size: text-font-size;
            text: "Version: \{version}\n\nLicense: \{license}\n\nHomePage: \{home_page}";
        }

        AboutSlint {
            vertical-stretch: 1.0;
        }

        HorizontalBox {
            vertical-stretch: 0.0;
            Window {
                horizontal-stretch: 1.0;
            }

            StandardButton {
                horizontal-stretch: 0.0;
                kind: StandardButtonKind.close;
                clicked => {
                    root.close();
                }
            }

            Window {
                horizontal-stretch: 1.0;
            }
        }
    }
}
