import {
    Button,
    StandardButton,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";

import { GameState } from "types.slint";

export component StateDialog inherits Dialog {
    title: state == GameState.Lose ? "Game Over" : state == GameState.Win ? "You Win" : "Unknown";
    in property <GameState> state;
    in property <length> text-font-size: self.default-font-size;
    icon: @image-url("resources/icons/info.svg");
    callback close();
    VerticalBox {
        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            vertical-stretch: 0.0;
            font-size: text-font-size;
            text: "\{root.title}";
            color: state == GameState.Lose ? brown : state == GameState.Win ? green : white;
        }

        Window {
            vertical-stretch: 1.0;
        }

        HorizontalBox {
            vertical-stretch: 0.0;
            Window {
                horizontal-stretch: 1.0;
            }

            StandardButton {
                horizontal-stretch: 0.0;
                kind: StandardButtonKind.close;
                clicked => {
                    root.close();
                }
            }

            Window {
                horizontal-stretch: 1.0;
            }
        }
    }
}
